//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyReg
    {
        public int C_Id { get; set; }
        public string C_Name { get; set; }
        public string C_Address { get; set; }
        public string C_Email { get; set; }
        public string C_Website { get; set; }
        public string C_Contact { get; set; }
    }
}
