//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Address { get; set; }
        public string User_Email { get; set; }
        public string User_Contact { get; set; }
        public string Gender { get; set; }
        public string State { get; set; }
        public string Qualification { get; set; }
        public string Skills { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string Photo { get; set; }
    }
}
